// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uusztmgzoaowysrxkuox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1c3p0bWd6b2Fvd3lzcnhrdW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzI0MDUsImV4cCI6MjA3MTcwODQwNX0.5OyYby1A6GTyZ6KgKdmAHm4oAWrme5oBpmsiFx3NP4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});